on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t containerscan24.azurecr.io/tipsandtrickscontainer
      
    - uses: Azure/container-scan@v0
      id: container-scan
      continue-on-error: true
      with:
        image-name: containerscan24.azurecr.io/tipsandtrickscontainer 
    
    - uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }} 
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: docker push containerscan24.azurecr.io/tipsandtrickscontainer       
