on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t containerscan25.azurecr.io/tipsandtrickscontainer:${{ github.sha }} 
      
    - uses: Azure/container-scan@v0
      id: container-scan
      continue-on-error: true
      with:
        image-name: containerscan25.azurecr.io/tipsandtrickscontainer:${{ github.sha }}  
    
    - uses: Azure/docker-login@v1
      with:
        login-server: containerscan25.azurecr.io 
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: docker push containerscan25.azurecr.io/tipsandtrickscontainer:${{ github.sha }}       

  #  - name: Post logs to appinsights
  #   uses: Azure/publish-security-assessments@v0
  #   with: 
  #      scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
   #     connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
     #   subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}                 
